# This workflow will do system level testing and linting for the cards bot functions (game threads, sidebar, draft)
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# Author: sweickge

name: Cardinals Bot CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install -y latexmk
    - name: Test
      run: |
        export EXPORTDIR=`pwd`/public
        mkdir -p $EXPORTDIR
        cd rulebook
        latexmk -pdf rulebook.tex
        mv rulebook.pdf $EXPORTDIR/rulebook.pdf

